// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.2
// source: first/Employee.proto

package EmployeePB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	No            int32                  `protobuf:"varint,2,opt,name=no,proto3" json:"no,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Salary        float32                `protobuf:"fixed32,5,opt,name=salary,proto3" json:"salary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_first_Employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_first_Employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_first_Employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetSalary() float32 {
	if x != nil {
		return x.Salary
	}
	return 0
}

type GetByNoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int32                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByNoRequest) Reset() {
	*x = GetByNoRequest{}
	mi := &file_first_Employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByNoRequest) ProtoMessage() {}

func (x *GetByNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_first_Employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByNoRequest.ProtoReflect.Descriptor instead.
func (*GetByNoRequest) Descriptor() ([]byte, []int) {
	return file_first_Employee_proto_rawDescGZIP(), []int{1}
}

func (x *GetByNoRequest) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_first_Employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_first_Employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_first_Employee_proto_rawDescGZIP(), []int{2}
}

func (x *EmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_first_Employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_first_Employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_first_Employee_proto_rawDescGZIP(), []int{3}
}

type AddPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPhotoRequest) Reset() {
	*x = AddPhotoRequest{}
	mi := &file_first_Employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPhotoRequest) ProtoMessage() {}

func (x *AddPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_first_Employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPhotoRequest.ProtoReflect.Descriptor instead.
func (*AddPhotoRequest) Descriptor() ([]byte, []int) {
	return file_first_Employee_proto_rawDescGZIP(), []int{4}
}

func (x *AddPhotoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPhotoResponse) Reset() {
	*x = AddPhotoResponse{}
	mi := &file_first_Employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPhotoResponse) ProtoMessage() {}

func (x *AddPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_first_Employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPhotoResponse.ProtoReflect.Descriptor instead.
func (*AddPhotoResponse) Descriptor() ([]byte, []int) {
	return file_first_Employee_proto_rawDescGZIP(), []int{5}
}

func (x *AddPhotoResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

type EmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeRequest) Reset() {
	*x = EmployeeRequest{}
	mi := &file_first_Employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeRequest) ProtoMessage() {}

func (x *EmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_first_Employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeRequest.ProtoReflect.Descriptor instead.
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return file_first_Employee_proto_rawDescGZIP(), []int{6}
}

func (x *EmployeeRequest) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

var File_first_Employee_proto protoreflect.FileDescriptor

const file_first_Employee_proto_rawDesc = "" +
	"\n" +
	"\x14first/Employee.proto\"|\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x0e\n" +
	"\x02no\x18\x02 \x01(\x05R\x02no\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12\x16\n" +
	"\x06salary\x18\x05 \x01(\x02R\x06salary\" \n" +
	"\x0eGetByNoRequest\x12\x0e\n" +
	"\x02no\x18\x01 \x01(\x05R\x02no\"9\n" +
	"\x10EmployeeResponse\x12%\n" +
	"\bemployee\x18\x01 \x01(\v2\t.EmployeeR\bemployee\"\x0f\n" +
	"\rGetAllRequest\"%\n" +
	"\x0fAddPhotoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"&\n" +
	"\x10AddPhotoResponse\x12\x12\n" +
	"\x04isOk\x18\x01 \x01(\bR\x04isOk\"8\n" +
	"\x0fEmployeeRequest\x12%\n" +
	"\bemployee\x18\x01 \x01(\v2\t.EmployeeR\bemployee2\xff\x01\n" +
	"\x0fEmployeeService\x12-\n" +
	"\aGetByNo\x12\x0f.GetByNoRequest\x1a\x11.EmployeeResponse\x12-\n" +
	"\x06GetAll\x12\x0e.GetAllRequest\x1a\x11.EmployeeResponse0\x01\x121\n" +
	"\bAddPhoto\x12\x10.AddPhotoRequest\x1a\x11.AddPhotoResponse(\x01\x12+\n" +
	"\x04Save\x12\x10.EmployeeRequest\x1a\x11.EmployeeResponse\x12.\n" +
	"\aSaveAll\x12\x10.EmployeeRequest\x1a\x11.EmployeeResponseB\x0fZ\r./;EmployeePBb\x06proto3"

var (
	file_first_Employee_proto_rawDescOnce sync.Once
	file_first_Employee_proto_rawDescData []byte
)

func file_first_Employee_proto_rawDescGZIP() []byte {
	file_first_Employee_proto_rawDescOnce.Do(func() {
		file_first_Employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_first_Employee_proto_rawDesc), len(file_first_Employee_proto_rawDesc)))
	})
	return file_first_Employee_proto_rawDescData
}

var file_first_Employee_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_first_Employee_proto_goTypes = []any{
	(*Employee)(nil),         // 0: Employee
	(*GetByNoRequest)(nil),   // 1: GetByNoRequest
	(*EmployeeResponse)(nil), // 2: EmployeeResponse
	(*GetAllRequest)(nil),    // 3: GetAllRequest
	(*AddPhotoRequest)(nil),  // 4: AddPhotoRequest
	(*AddPhotoResponse)(nil), // 5: AddPhotoResponse
	(*EmployeeRequest)(nil),  // 6: EmployeeRequest
}
var file_first_Employee_proto_depIdxs = []int32{
	0, // 0: EmployeeResponse.employee:type_name -> Employee
	0, // 1: EmployeeRequest.employee:type_name -> Employee
	1, // 2: EmployeeService.GetByNo:input_type -> GetByNoRequest
	3, // 3: EmployeeService.GetAll:input_type -> GetAllRequest
	4, // 4: EmployeeService.AddPhoto:input_type -> AddPhotoRequest
	6, // 5: EmployeeService.Save:input_type -> EmployeeRequest
	6, // 6: EmployeeService.SaveAll:input_type -> EmployeeRequest
	2, // 7: EmployeeService.GetByNo:output_type -> EmployeeResponse
	2, // 8: EmployeeService.GetAll:output_type -> EmployeeResponse
	5, // 9: EmployeeService.AddPhoto:output_type -> AddPhotoResponse
	2, // 10: EmployeeService.Save:output_type -> EmployeeResponse
	2, // 11: EmployeeService.SaveAll:output_type -> EmployeeResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_first_Employee_proto_init() }
func file_first_Employee_proto_init() {
	if File_first_Employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_first_Employee_proto_rawDesc), len(file_first_Employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_first_Employee_proto_goTypes,
		DependencyIndexes: file_first_Employee_proto_depIdxs,
		MessageInfos:      file_first_Employee_proto_msgTypes,
	}.Build()
	File_first_Employee_proto = out.File
	file_first_Employee_proto_goTypes = nil
	file_first_Employee_proto_depIdxs = nil
}
