// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.2
// source: first/person.proto

package EmployeePB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_NOT_SPECIFIED Gender = 0
	Gender_WoMAN         Gender = 1
	Gender_MAN           Gender = 2
	Gender_FEMALE        Gender = 1
	Gender_MALE          Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "NOT_SPECIFIED",
		1: "WoMAN",
		2: "MAN",
		// Duplicate value: 1: "FEMALE",
		// Duplicate value: 2: "MALE",
	}
	Gender_value = map[string]int32{
		"NOT_SPECIFIED": 0,
		"WoMAN":         1,
		"MAN":           2,
		"FEMALE":        1,
		"MALE":          2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_first_person_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_first_person_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_first_person_proto_rawDescGZIP(), []int{0}
}

type PersonMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsAdult       bool                   `protobuf:"varint,2,opt,name=is_adult,json=isAdult,proto3" json:"is_adult,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	LuckyNumber   []int32                `protobuf:"varint,4,rep,packed,name=lucky_number,json=luckyNumber,proto3" json:"lucky_number,omitempty"`
	Gender        Gender                 `protobuf:"varint,5,opt,name=gender,proto3,enum=first.Gender" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonMessage) Reset() {
	*x = PersonMessage{}
	mi := &file_first_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonMessage) ProtoMessage() {}

func (x *PersonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_first_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonMessage.ProtoReflect.Descriptor instead.
func (*PersonMessage) Descriptor() ([]byte, []int) {
	return file_first_person_proto_rawDescGZIP(), []int{0}
}

func (x *PersonMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonMessage) GetIsAdult() bool {
	if x != nil {
		return x.IsAdult
	}
	return false
}

func (x *PersonMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonMessage) GetLuckyNumber() []int32 {
	if x != nil {
		return x.LuckyNumber
	}
	return nil
}

func (x *PersonMessage) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_NOT_SPECIFIED
}

var File_first_person_proto protoreflect.FileDescriptor

const file_first_person_proto_rawDesc = "" +
	"\n" +
	"\x12first/person.proto\x12\x05first\"\x98\x01\n" +
	"\rPersonMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bis_adult\x18\x02 \x01(\bR\aisAdult\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\flucky_number\x18\x04 \x03(\x05R\vluckyNumber\x12%\n" +
	"\x06gender\x18\x05 \x01(\x0e2\r.first.GenderR\x06gender*I\n" +
	"\x06Gender\x12\x11\n" +
	"\rNOT_SPECIFIED\x10\x00\x12\t\n" +
	"\x05WoMAN\x10\x01\x12\a\n" +
	"\x03MAN\x10\x02\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x01\x12\b\n" +
	"\x04MALE\x10\x02\x1a\x02\x10\x01B\rZ\v./;PersonPBb\x06proto3"

var (
	file_first_person_proto_rawDescOnce sync.Once
	file_first_person_proto_rawDescData []byte
)

func file_first_person_proto_rawDescGZIP() []byte {
	file_first_person_proto_rawDescOnce.Do(func() {
		file_first_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_first_person_proto_rawDesc), len(file_first_person_proto_rawDesc)))
	})
	return file_first_person_proto_rawDescData
}

var file_first_person_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_first_person_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_first_person_proto_goTypes = []any{
	(Gender)(0),           // 0: first.Gender
	(*PersonMessage)(nil), // 1: first.PersonMessage
}
var file_first_person_proto_depIdxs = []int32{
	0, // 0: first.PersonMessage.gender:type_name -> first.Gender
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_first_person_proto_init() }
func file_first_person_proto_init() {
	if File_first_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_first_person_proto_rawDesc), len(file_first_person_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_first_person_proto_goTypes,
		DependencyIndexes: file_first_person_proto_depIdxs,
		EnumInfos:         file_first_person_proto_enumTypes,
		MessageInfos:      file_first_person_proto_msgTypes,
	}.Build()
	File_first_person_proto = out.File
	file_first_person_proto_goTypes = nil
	file_first_person_proto_depIdxs = nil
}
